use std::path::Path;
use tauri::Window;
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command;

#[tauri::command]
pub async fn export_web(project_dir: String, out_dir: String) -> Result<(), String> {
    if !Path::new(&project_dir).join("node_modules").exists() {
        let install = Command::new("bun")
            .arg("install")
            .current_dir(&project_dir)
            .status()
            .await
            .map_err(|e| format!("Bun install error: {}", e))?;

        if !install.success() {
            return Err("bun install failed".to_string());
        }
    }

    let status = Command::new("bun")
        .args(["x", "vite", "build", "--outDir", &out_dir])
        .current_dir(&project_dir)
        .status()
        .await
        .map_err(|e| format!("Vite build error: {}", e))?;

    if !status.success() {
        return Err("Web export build failed".to_string());
    }

    Ok(())
}

#[tauri::command]
pub async fn export_desktop(
    project_dir: String,
    target_triple: String,
    out_dir: String,
    window: Window,
) -> Result<(), String> {
    let _ = window.emit(
        "build-log",
        format!("Cross-compiling for {}...", target_triple),
    );

    let mut child = Command::new("cargo")
        .args([
            "build",
            "-p",
            "retro-platform-native",
            "--target",
            &target_triple,
            "--release",
        ])
        .current_dir(&project_dir)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to start cargo: {}", e))?;

    if let Some(stderr) = child.stderr.take() {
        let reader = BufReader::new(stderr);
        let mut lines = reader.lines();
        while let Ok(Some(line)) = lines.next_line().await {
            let _ = window.emit("build-log", &line);
        }
    }

    let status = child
        .wait()
        .await
        .map_err(|e| format!("Build error: {}", e))?;

    if !status.success() {
        return Err(format!("Desktop export for {} failed", target_triple));
    }

    // Copy binary to out_dir
    let binary_name = if target_triple.contains("windows") {
        "retro-platform-native.exe"
    } else {
        "retro-platform-native"
    };

    let binary_src = Path::new(&project_dir)
        .join("target")
        .join(&target_triple)
        .join("release")
        .join(binary_name);

    let out = Path::new(&out_dir);
    std::fs::create_dir_all(out).map_err(|e| format!("mkdir error: {}", e))?;

    if binary_src.exists() {
        std::fs::copy(&binary_src, out.join(binary_name))
            .map_err(|e| format!("Copy error: {}", e))?;
    }

    let _ = window.emit("build-log", format!("Desktop export complete: {}", out_dir));
    Ok(())
}

#[tauri::command]
pub async fn export_rom_ready(
    _project_dir: String,
    platform: String,
    out_dir: String,
) -> Result<(), String> {
    let out = Path::new(&out_dir);
    std::fs::create_dir_all(out).map_err(|e| format!("mkdir error: {}", e))?;

    match platform.as_str() {
        "gb" => generate_gb_scaffold(out)?,
        "nes" => generate_nes_scaffold(out)?,
        _ => {
            return Err(format!(
                "Unknown ROM platform: {}. Use 'gb' or 'nes'.",
                platform
            ))
        }
    }

    Ok(())
}

fn generate_gb_scaffold(out: &Path) -> Result<(), String> {
    std::fs::create_dir_all(out.join("assets")).map_err(|e| format!("mkdir: {}", e))?;
    std::fs::create_dir_all(out.join("maps")).map_err(|e| format!("mkdir: {}", e))?;

    std::fs::write(
        out.join("Makefile"),
        r#"GBDK_HOME ?= /opt/gbdk
CC = $(GBDK_HOME)/bin/lcc
ROM_NAME = game.gb
SRCS = main.c

all: $(ROM_NAME)

$(ROM_NAME): $(SRCS)
	$(CC) -o $@ $^

clean:
	rm -f $(ROM_NAME)

.PHONY: all clean
"#,
    )
    .map_err(|e| format!("write: {}", e))?;

    std::fs::write(
        out.join("main.c"),
        r#"#include <gb/gb.h>
#include <stdio.h>

void main(void) {
    DISPLAY_ON;
    BGP_REG = 0xE4U;
    OBP0_REG = 0xE4U;
    printf("RETRO ENGINE\nGB ROM READY\n");
    while(1) {
        UINT8 keys = joypad();
        wait_vbl_done();
    }
}
"#,
    )
    .map_err(|e| format!("write: {}", e))?;

    std::fs::write(
        out.join("README.md"),
        r#"# Game Boy ROM Project

Generated by retro-engine editor.

## Prerequisites
1. Install GBDK-2020: https://github.com/gbdk-2020/gbdk-2020/releases
2. Set `GBDK_HOME` environment variable

## Build
```bash
export GBDK_HOME=/path/to/gbdk
make
```
"#,
    )
    .map_err(|e| format!("write: {}", e))?;

    Ok(())
}

fn generate_nes_scaffold(out: &Path) -> Result<(), String> {
    std::fs::create_dir_all(out.join("chr")).map_err(|e| format!("mkdir: {}", e))?;
    std::fs::create_dir_all(out.join("maps")).map_err(|e| format!("mkdir: {}", e))?;

    std::fs::write(
        out.join("Makefile"),
        r#"CC65_HOME ?= /opt/cc65
CC = $(CC65_HOME)/bin/cc65
AS = $(CC65_HOME)/bin/ca65
LD = $(CC65_HOME)/bin/ld65
ROM_NAME = game.nes
SRCS = main.c

all: $(ROM_NAME)

%.s: %.c
	$(CC) -Oi -t nes -o $@ $<
%.o: %.s
	$(AS) -t nes -o $@ $<

$(ROM_NAME): main.o nes.cfg
	$(LD) -C nes.cfg -o $@ main.o nes.lib

clean:
	rm -f $(ROM_NAME) *.o *.s

.PHONY: all clean
"#,
    )
    .map_err(|e| format!("write: {}", e))?;

    std::fs::write(
        out.join("main.c"),
        r#"#include "neslib.h"

const unsigned char palette[16] = {
  0x0F,0x11,0x21,0x30, 0x0F,0x06,0x16,0x26,
  0x0F,0x09,0x19,0x29, 0x0F,0x01,0x11,0x21
};

void main(void) {
  pal_bg(palette);
  ppu_on_all();
  while(1) {
    ppu_wait_nmi();
    unsigned char pad = pad_poll(0);
  }
}
"#,
    )
    .map_err(|e| format!("write: {}", e))?;

    std::fs::write(
        out.join("nes.cfg"),
        r#"MEMORY {
    ZP:  start=$0000, size=$0100, type=rw, define=yes;
    RAM: start=$0200, size=$0600, type=rw, define=yes;
    HDR: start=$0000, size=$0010, type=ro, file=%O, fill=yes;
    PRG: start=$8000, size=$8000, type=ro, file=%O, fill=yes;
    CHR: start=$0000, size=$2000, type=ro, file=%O, fill=yes;
}
SEGMENTS {
    ZEROPAGE: load=ZP, type=zp;
    BSS:      load=RAM, type=bss, define=yes;
    HEADER:   load=HDR, type=ro;
    CODE:     load=PRG, type=ro, start=$8000;
    RODATA:   load=PRG, type=ro;
    VECTORS:  load=PRG, type=ro, start=$FFFA;
    CHARS:    load=CHR, type=ro;
}
"#,
    )
    .map_err(|e| format!("write: {}", e))?;

    std::fs::write(
        out.join("README.md"),
        r#"# NES ROM Project

Generated by retro-engine editor.

## Prerequisites
1. Install cc65: https://cc65.github.io/
2. Install NESLib: https://github.com/clbr/neslib
3. Set `CC65_HOME` environment variable

## Build
```bash
export CC65_HOME=/path/to/cc65
make
```
"#,
    )
    .map_err(|e| format!("write: {}", e))?;

    Ok(())
}
